#### Stage 1: Build the application
# FROM adoptopenjdk/openjdk11:alpine-jre
# COPY target/hospital-backend.jar hospital-backend.jar
# ENTRYPOINT ["java","-jar","/hospital-backend.jar"]
FROM openjdk:8-alpine
add target/*.jar BSSB.jar
ENTRYPOINT ["java","-jar","BSSB.jar"]
   
